name: Generate documentation
on: 
  workflow_dispatch:
    branches: [ main ]

jobs:
  generate-documentation:
    name: Generate documentation
    runs-on: ubuntu-latest
    steps:
    - name: Run Doxygen
      uses: mattnotmitt/doxygen-action@v1.9.2
      with:
        working-directory: '/src/'
        doxyfile-path: '/docs/'
